### ISSUE TITLE
Why command has reference to view

### ISSUE THREAD

**Issue by VladimirCores** [PureMVC/puremvc-as3-standard-framework#2]
Why do not create separate method for command execution like - sendCommand?

**Comment by mbritton** [comment]
Good idea. Where would you do this?

**Comment by VladimirCores** [comment]
Inside facade of course

**Comment by cliffhall** [comment]
I don't understand the question. SimpleCommand and MacroCommand have a reference to Facade, so that they can send commands. Those classes do not have a direct reference to View.

**Comment by VladimirCores** [comment]
It's because i like to separate command execution notifications from "normal" notification that only notify mediators. This idea realized in mvcexpress framework http://mvcexpress.org/

**Comment by cliffhall** [comment]
In the MVC paradigm, the Model can notify either the View or Controller. In the case of PureMVC's architecture, an ICommand (in the Controller) OR multiple Mediators (in the View) may respond to any notification. 

Because of this, the Model is able to notify the View or Controller areas of the app without needing to make the distinction about who the recipient will be. This decouples the Model from the rest of the application, making the Model - the crown jewels of the app - portable. This is good because you can take your Proxies and Value Objects and Enums off and use them in any number of applications.

Consider a Proxy that retrieves data from the server then passes it to the rest of the app for use. You might use this in a mobile app, a desktop app, and a browser app, each with different UI and business logic. 

In one application that uses this Proxy, an ICommand might respond to the Proxy's notification that the data has been retrieved, process it in some way, and then send another notification to the View with the data in a consumable form. 

In another app, a Mediator might consume the notification directly and pass the data to its view component.

So it is good that the Model doesn't care who'll consume the notification. Separation of notification types between View and Controller are not required, and I really can't think of a good argument for inclusion of such a separation in the framework itself. That separation would add complexity, and complexity is the beast we are fighting, that has taken the blood and the life from many a fallen comrade in code. Thus, we must find the balance between complexity and functionality that gives us an implementation of MVC that achieves the goal of separating the UI, Logic, and Data and allowing them to communicate with one another in a simple protocol.

**Comment by VladimirCores** [comment]
I fully agree with your argument and i understand all princeples discribed in your book about framework usage, but within a big project its confusing and a lot of time wast on finding what executes after notification send it's a command or mediator or both. That is why i seperate Commands and Notifications in different classes, because i cant import the same View or Controller classes in the model for different projects. This is not a problem at all, i just wish to have separated method inside framework for better commands and meditors calling, maybe better methods naming because mediators has notifications list and commands "bind" to notifications as well but in the most cases they do different things, and also this.sendNotifiication(Notification.PLAY_CONNECTED, playerVO) or sendCommand(Commands.PLAYER_CONNECT_REQUEST, playerID) is not a good choice. It's because i like that conception and always think about better way of doing my art.

**Comment by cliffhall** [comment]
Construction of the framework has taken Einstein's advice: "As simple as possible, but no simpler." We needed an internal message passing system, so we built it as simply as we could. Arguably, creating a separation of message types makes it more complex, and hence goes against the simplicity mandate.

That said, the framework is open source, so you can certainly modify it do behave the way you want.

**Comment by mbritton** [comment]
Definitely mod it! A plugin architecture / API would also be very helpful.

## Mike Britton

@mbritton
http://www.mikebritton.com
http://www.google.com/profiles/mbritton72

**Comment by VladimirCores** [comment]
"That said, the framework is open source, so you can certainly modify it do behave the way you want."

I plan to modify and extend your framework but save the main concept and structure. What kind of licence i need to use for this?

**Comment by cliffhall** [comment]
https://raw.githubusercontent.com/PureMVC/puremvc-as3-standard-framework/master/LICENSE
